function buildPrompt({ documentType }) {
  return [
    "You are extracting structured data from a PDF.",
    "Return ONLY a valid JSON object (no markdown, no code fences, no extra text).",
    "If a field is missing, use null (do not invent values).",
    "",
    "General rules:",
    "- Dates must be in YYYY-MM-DD format (string).",
    "- Quantities must be numbers.",
    "- Do NOT confuse item codes with quantities. Quantity must come from the Qty/Quantity column.",
    "- Do NOT drop digits (e.g. 640 must not become 40).",
    "- Return one JSON item per row. Do not merge rows.",
    "- Join words split by PDF line breaks (e.g., 'Win gs' -> 'Wings', 'Breas t' -> 'Breast').",
    "- Keep important product words and pack size/UOM (e.g. '250g', '24 pcs').",
    "- Do NOT generate match keys. Just extract fields cleanly.",
    "- cleanDescription must be a cleaned version of rawDescription (spacing fixed). Do not invent meaning.",
    "- items must be an array (empty if none).",
    "",
    `Document type: ${documentType}`,
    "",
    "Required output shape by documentType:",
    "",
    "If documentType == 'po':",
    "{",
    '  "poNumber": "string|null",',
    '  "poDate": "YYYY-MM-DD|null",',
    '  "vendorName": "string|null",',
    '  "items": [ {',
    '    "sku": "string|null (numeric product code if present)",',
    '    "docItemCode": "string|null (exact code as shown in the PO line, if any)",',
    '    "rawDescription": "string|null (as seen on the row, with joined line breaks)",',
    '    "cleanDescription": "string|null (spacing fixed, keep pack size, no extra words)",',
    '    "quantity": 0',
    "  } ]",
    "}",
    "",
    "If documentType == 'grn':",
    "{",
    '  "grnNumber": "string|null",',
    '  "poNumber": "string|null",',
    '  "grnDate": "YYYY-MM-DD|null",',
    '  "items": [ {',
    '    "sku": "string|null (numeric product code if present)",',
    '    "docItemCode": "string|null (exact code as shown in the GRN line, if any)",',
    '    "rawDescription": "string|null (as seen on the row, with joined line breaks)",',
    '    "cleanDescription": "string|null (spacing fixed, keep pack size, no extra words)",',
    '    "receivedQuantity": 0',
    "  } ]",
    "}",
    "",
    "If documentType == 'invoice':",
    "{",
    '  "invoiceNumber": "string|null",',
    '  "poNumber": "string|null",',
    '  "invoiceDate": "YYYY-MM-DD|null",',
    '  "items": [ {',
    '    "sku": "string|null (numeric product code if present; otherwise null)",',
    '    "docItemCode": "string|null (invoice item code, e.g. FG-...)",',
    '    "rawDescription": "string|null (as seen on the row, with joined line breaks)",',
    '    "cleanDescription": "string|null (spacing fixed, keep pack size, no extra words)",',
    '    "quantity": 0',
    "  } ]",
    "}"
  ].join("\n");
}

module.exports = { buildPrompt };

